In [1]:
import numpy as np
from linop import *

In [2]:
size = 5
real1d = np.random.randn(size)
real2d = np.random.randn(size, size)
complex1d = np.random.randn(size) + 1j * np.random.randn(size)
complex2d = np.random.randn(size, size) + np.random.randn(size, size)

In [3]:
op_mat = LinOpMatrix(real2d)
op_mat2 = LinOpMatrix(complex2d)
op_mat.apply(real1d)
op_mat.apply(complex1d)
op_mat2.apply(real1d)
op_mat2.apply(complex1d)
op_mat2.apply(real2d);

In [4]:
op_mul = LinOpMul(real1d)
op_mul2 = LinOpMul(complex1d)
op_mul.apply(real1d)
op_mul.apply(real2d)
op_mul.apply(complex1d)
op_mul2.apply(real1d)
op_mul2.apply(complex1d);

In [5]:
op_fft = LinOpFFT()
op_fft2 = LinOpFFT2()
op_fft.apply(real1d)
op_fft.apply(complex1d)
op_fft2.apply(real2d)
op_fft2.apply(complex2d);

In [6]:
op_sum = op_mat + op_mul
op_diff = op_mat - op_mul
op_composition = op_mat @ op_mul
op_stack = StackLinOp([op_mat, op_mul])

In [7]:
temp = op_stack.apply(real1d)
op_stack.applyAdjoint(temp)

array([-0.10911585,  5.54945171,  0.15758712, -4.270622  ,  3.60347301])

In [8]:
op_flip = LinOpFlip()
print(real2d)
print(op_flip.apply(real2d))

[[-1.58717082  0.12535725  0.41564814  0.59283228 -2.30729284]
 [-1.69657926  0.10612592  0.45779423 -0.02744641 -0.15637853]
 [ 0.15746562 -1.06666734  0.06128307  0.25105988  1.35485648]
 [-0.23020773 -3.94633154  0.27753535  1.37247673 -0.65336671]
 [ 0.17804086 -1.53958279  0.02887502  0.71668654  1.20918136]]
[[ 1.20918136  0.71668654  0.02887502 -1.53958279  0.17804086]
 [-0.65336671  1.37247673  0.27753535 -3.94633154 -0.23020773]
 [ 1.35485648  0.25105988  0.06128307 -1.06666734  0.15746562]
 [-0.15637853 -0.02744641  0.45779423  0.10612592 -1.69657926]
 [-2.30729284  0.59283228  0.41564814  0.12535725 -1.58717082]]


In [9]:
op_roll = LinOpRoll(shifts=(1,2), dims=(0,1))
print(real2d)
print(op_roll.apply(real2d))

[[-1.58717082  0.12535725  0.41564814  0.59283228 -2.30729284]
 [-1.69657926  0.10612592  0.45779423 -0.02744641 -0.15637853]
 [ 0.15746562 -1.06666734  0.06128307  0.25105988  1.35485648]
 [-0.23020773 -3.94633154  0.27753535  1.37247673 -0.65336671]
 [ 0.17804086 -1.53958279  0.02887502  0.71668654  1.20918136]]
[[ 0.71668654  1.20918136  0.17804086 -1.53958279  0.02887502]
 [ 0.59283228 -2.30729284 -1.58717082  0.12535725  0.41564814]
 [-0.02744641 -0.15637853 -1.69657926  0.10612592  0.45779423]
 [ 0.25105988  1.35485648  0.15746562 -1.06666734  0.06128307]
 [ 1.37247673 -0.65336671 -0.23020773 -3.94633154  0.27753535]]


In [10]:
op_sum + 1
op_diff - 1
1 - op_diff
op_composition * 3
(3 * op_composition).in_size

5

In [11]:
x = np.random.randn(size)
compl_op = op_mat @ op_fft
y = compl_op.apply(x)